Version: v2
Parameters:
    - Name: "PgAdminPort"
      Type: integer
      Description: "Port for accessing pgAdmin"
      DefaultValue: 9001
      ConfigurationModes:
          - Basic
    - Name: "PgPort"
      Type: integer
      Description: "Port for accessing the PostgreSQL DBMS"
      DefaultValue: 5432
      ConfigurationModes:
          - Basic
    - Name: "PgUser"
      Type: string
      Description: "Username of a service account for accessing the PostgreSQL DBMS"
      DefaultValue: "pt_system"
      ConfigurationModes:
          - System
    - Name: "PgPassword"
      Type: string
      Description: "Password of a service account for accessing the PostgreSQL DBMS"
      DefaultValue: "P@ssw0rdP@ssw0rd"
      ConfigurationModes:
          - Basic
