// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Deployment struct {
	ID        string `json:"id"`
	HostID    string `json:"host_id"`
	PackageID string `json:"package_id"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Host struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Hostname   string `json:"hostname"`
	Port       int64  `json:"port"`
	Username   string `json:"username"`
	SshKeyPath string `json:"ssh_key_path"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type Log struct {
	ID           string `json:"id"`
	DeploymentID string `json:"deployment_id"`
	Timestamp    string `json:"timestamp"`
	Message      string `json:"message"`
}

type Package struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	ComposeContent string `json:"compose_content"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}
