Version: v2
Role:
    TypeId: SqlStorage
    Name: sqlstorage
    Version: 101.20.18991
    Description: SqlStorage
    Definitions:
        ImageFile: "images/SqlStorage_101.20.18991.tar"
        Images:
            - Id: storage-postgres
            - Id: storage-pgadmin
            - Id: observability.opentelemetry.collector.postgresql.agent
        TemplateFiles:
            - storage-postgres/config/default.env
            - storage-postgres/.env
            - storage-pgadmin/config/default.env
            - storage-pgadmin/.env
            - observability.opentelemetry.collector.postgresql.agent/config/default.env
            - observability.opentelemetry.collector.postgresql.agent/.env
